### ISSUE TITLE
input 다루기 2 : 블로그 글발행 기능 만들기

### ISSUE THREAD

**Issue by Yeonlisa** [Yeonlisa/Blog#11]
# 블로그 글 발행기능 만들기

(단! 서버 + DB가 없어서 영구저장 안되는 상황임)

1. 글은 변수나 state에 저장한다.
2. 글을 적을 수 있는 UI를 만든다.

```jsx
function App (){
  let [글제목, 글제목변경] = useState(['남자코트추천', '강남우동맛집', '리액트 독학']);
  return (
    <div>
      HTML 잔뜩 있는 곳
      <div className="publish">
        <input />
        <button>저장</button>
      </div>
    </div>
  )
}
```

```css
.publish {
  margin-top : 30px;
  margin-bottom : 30px;
}
.publish input {
  padding : 10px;
  font-size : 16px;
  border-radius : 5px;
  width : 80%;
  border : 1px solid grey;
}
.publish button {
  display : block;
  margin : auto;
  margin-top : 10px;
}
```

<aside>
💡 실전에선 서버로 먼저 보내서 영구 저장한다

</aside>

1. 글적고 저장버튼누르면 글이 위에 하나 더 뜨게끔 기능을 만든다. (글적고 저장버튼누르면 글이 위에 떠야함)
    
    3-1. 사용자가 입력한 글 state로 저장하기
    
    ```jsx
    function App (){
      let [글제목, 글제목변경] = useState(['남자코트추천', '강남우동맛집', '리액트 독학']);
      let [입력값, 입력값변경] = useState('');
      return (
        <div>
          HTML 잔뜩 있는 곳
          <div className="publish">
            <input onChange={ (e)=>{ 입력값변경(e.target.value) } } />
            <button>저장</button>
          </div>
        </div>
      )
    }
    ```
    
    3-2. 버튼누르면 입력한 글 state를 글제목 state에 추가함
    
    ```jsx
    function App (){
      let [글제목, 글제목변경] = useState(['남자코트추천', '강남우동맛집', '리액트 독학']);
      let [입력값, 입력값변경] = useState('');
      return (
        <div>
          HTML 잔뜩 있는 곳
          <div className="publish">
            <input onChange={ (e)=>{ 입력값변경(e.target.value) } } />
            <button onClick={ ()=>{ 글제목변경(???) }}>저장</button>
          </div>
        </div>
      )
    }
    ```
    
    3-3. array 맨앞에 자료 추가하는 문법인 `unshift()` 사용한다.
    
    3-4. state 데이터는 `=` 등호로 직접 수정이 불가하기 때문에 사본(spread syntax 사용)을 만들어 사본을 수정한다.
    
    ```jsx
    function App (){
      let [글제목, 글제목변경] = useState(['남자코트추천', '강남우동맛집', '리액트 독학']);
      let [입력값, 입력값변경] = useState('');
      return (
        <div>
          HTML 잔뜩 있는 곳
          <div className="publish">
            <input onChange={ (e)=>{ 입력값변경(e.target.value) } } />
            <button onClick={ ()=>{ 
    
              let arrayCopy = [...글제목];
              arrayCopy.unshift(입력값);
              글제목변경( arrayCopy )
    
             }}>저장</button>
          </div>
        </div>
      )
    }
    ```
